//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YuriyGuts.UnicodeKeyboard.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YuriyGuts.UnicodeKeyboard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://famfamfam.com/lab/icons/silk/.
        /// </summary>
        internal static string AboutForm_SilkIconsURL {
            get {
                return ResourceManager.GetString("AboutForm_SilkIconsURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://unicode.org/ucd/.
        /// </summary>
        internal static string AboutForm_UnicodeCharacterDatabaseURL {
            get {
                return ResourceManager.GetString("AboutForm_UnicodeCharacterDatabaseURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.codeproject.com/KB/cs/globalhook.aspx.
        /// </summary>
        internal static string AboutForm_UserActivityMonitorURL {
            get {
                return ResourceManager.GetString("AboutForm_UserActivityMonitorURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicode Virtual Keyboard.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0 b2.
        /// </summary>
        internal static string ApplicationVersion {
            get {
                return ResourceManager.GetString("ApplicationVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CharacterNamesCompressed {
            get {
                object obj = ResourceManager.GetObject("CharacterNamesCompressed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © Yuriy Guts, 2010-2011.
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Crosshair {
            get {
                object obj = ResourceManager.GetObject("Crosshair", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CrosshairCursor {
            get {
                object obj = ResourceManager.GetObject("CrosshairCursor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KeyboardSmall {
            get {
                object obj = ResourceManager.GetObject("KeyboardSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon KeyboardSmallIcon {
            get {
                object obj = ResourceManager.GetObject("KeyboardSmallIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KeyShortcutAddToFavorites {
            get {
                object obj = ResourceManager.GetObject("KeyShortcutAddToFavorites", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KeyShortcutCopyToClipboard {
            get {
                object obj = ResourceManager.GetObject("KeyShortcutCopyToClipboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KeyShortcutInsertCharacter {
            get {
                object obj = ResourceManager.GetObject("KeyShortcutInsertCharacter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Language_EN_US {
            get {
                return ResourceManager.GetString("Language_EN_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский (Russian).
        /// </summary>
        internal static string Language_RU_RU {
            get {
                return ResourceManager.GetString("Language_RU_RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Українська (Ukrainian).
        /// </summary>
        internal static string Language_UK_UA {
            get {
                return ResourceManager.GetString("Language_UK_UA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start Character Map because of an error..
        /// </summary>
        internal static string MainForm_msgCharmapLaunchFailed {
            get {
                return ResourceManager.GetString("MainForm_msgCharmapLaunchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send the character to the target window..
        /// </summary>
        internal static string MainForm_msgSendCharFailed {
            get {
                return ResourceManager.GetString("MainForm_msgSendCharFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (unknown).
        /// </summary>
        internal static string MainForm_strNoTargetWindow {
            get {
                return ResourceManager.GetString("MainForm_strNoTargetWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MouseShortcutInsertCharacter {
            get {
                object obj = ResourceManager.GetObject("MouseShortcutInsertCharacter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The primary and secondary shortcuts must be different..
        /// </summary>
        internal static string OptionsForm_msgDuplicateKeyboardShortcuts {
            get {
                return ResourceManager.GetString("OptionsForm_msgDuplicateKeyboardShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid primary shortcut. Please choose another one..
        /// </summary>
        internal static string OptionsForm_msgInvalidPrimaryShortcut {
            get {
                return ResourceManager.GetString("OptionsForm_msgInvalidPrimaryShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid secondary shortcut. Please choose another one..
        /// </summary>
        internal static string OptionsForm_msgInvalidSecondaryShortcut {
            get {
                return ResourceManager.GetString("OptionsForm_msgInvalidSecondaryShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to restart the application for the new language settings to take effect. Restart the application now?.
        /// </summary>
        internal static string OptionsForm_msgLanguageSettingsAppRestartConfirmation {
            get {
                return ResourceManager.GetString("OptionsForm_msgLanguageSettingsAppRestartConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Wrench {
            get {
                object obj = ResourceManager.GetObject("Wrench", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
